# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import idm_auth.onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20170623_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingactivation',
            name='activation_code',
            field=models.CharField(db_index=True, default=idm_auth.onboarding.models.new_activation_code, max_length=14, unique=True),
        ),
    ]
