# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDP',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256)),
                ('entity_id', models.URLField()),
                ('url', models.URLField()),
                ('x509cert', models.TextField()),
            ],
        ),
    ]
