# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('identity_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
