# Generated by Django 2.2.2 on 2019-06-28 13:53

from django.db import migrations, models
import forsta_auth.onboarding.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('identity_id', models.UUIDField(db_index=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activation_code', models.CharField(db_index=True, default=forsta_auth.onboarding.models.new_activation_code, max_length=14, unique=True)),
            ],
        ),
    ]
