# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_pendingactivation_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingactivation',
            name='user',
        ),
        migrations.AddField(
            model_name='pendingactivation',
            name='identity_id',
            field=models.UUIDField(db_index=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
