# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
            preserve_default=False,
        ),
    ]
