# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm_auth', '0004_auto_20170427_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
